spring:
  application:
    name: JwtService

server:
  port: 9300

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/


ribbon.ReadTimeout: 50000
ribbon.ConnectTimeout: 50000

jwt:
  password: adfkd#23
  token:
    expire: 1440


