version: '2'
services:
  eurekaserver1:
    image: eureka-server:1.0.0
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eureka_1

  eurekaserver2:
    image: eureka-server:1.0.0
    #hostname: eurekaserver2
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=eureka_2

  zuulserver1:
    image: zuul-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "8081:8080"

  zuulserver2:
    image: zuul-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
        - "8082:8080"

  configserver1:
    image: config-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9000:9000"

  configserver2:
    image: config-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9001:9000"