version: '2'
services:
  eurekaserver1:
    image: eureka-server:1.0.0
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=eureka_1

  eurekaserver2:
    image: eureka-server:1.0.0
    #hostname: eurekaserver2
    ports:
      - "8763:8761"
    environment:
      - spring.profiles.active=eureka_2