version: '2'
services:
  eurekaserver1:
    image: eureka-server:1.0.0
    ports:
      - "8761:8761"
    environment:
      - spring.profiles.active=eureka_1

  eurekaserver2:
    image: eureka-server:1.0.0
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=eureka_2

  configserver1:
    image: config-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9010:9010"

  configserver2:
    image: config-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9011:9010"

  zuulserver1:
    image: zuul-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9090:9090"

  zuulserver2:
    image: zuul-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9091:9090"

  zipkinserver1:
    image: zipkin-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9020:9020"

  zipkinserver2:
    image: zipkin-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
    ports:
      - "9021:9020"


  userserver1:
    image: user-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
      - configserver1
    ports:
      - "9030:9030"
    environment:
      - spring.cloud.config.profile=test

  userserver2:
    image: user-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
      - configserver1
    ports:
      - "9031:9030"
    environment:
      - spring.cloud.config.profile=test

  jwtserver1:
    image: jwt-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
      - userserver1
    ports:
      - "9040:9040"

  jwtserver2:
    image: jwt-server:1.0.0
    command: java -Djava.security.egd=file:/dev/./urandom -jar /app.jar --eureka.host=eurekaserver1 --eureka.port=8761
    depends_on:
      - eurekaserver1
      - userserver2
    ports:
      - "9041:9040"