version: '2'
services:
  eurekaserver1:
    image: eureka-server:1.0.0
    ports:
      - "8762:8761"
    environment:
      - spring.profiles.active=eureka_1

  eurekaserver2:
    image: eureka-server:1.0.0
    #hostname: eurekaserver2
    ports:
      - "8763:8761"
    environment:
      - spring.profiles.active=eureka_2

  zuulserver1:
    image: zuul-server:1.0.0
    depends_on:
      - eurekaserver1
    ports:
      - "8080:8080"

  zuulserver2:
    image: zuul-server:1.0.0
    depends_on:
      - eurekaserver1
    ports:
        - "8081:8080"

  configserver1:
    image: config-server:1.0.0
    depends_on:
      - eurekaserver1
    ports:
      - "9000:9000"

  configserver1:
    image: config-server:1.0.0
    depends_on:
      - eurekaserver1
    ports:
      - "9001:9000"