spring:
  rabbitmq:
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9700
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/userdb?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    schema:
    data: classpath:db/data.sql

logging:
  level:
    com.androidminds.smartservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file: /var/smartservice/UserService.log

server:
  port: 9030

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

userservice:
  max-page-count: 50
