spring:
  rabbitmq:
    host: localhost
    port: 5672
  zipkin:
    base-url: http://localhost:9700
  spring:
    jpa:
      database: MYSQL
      show-sql: true
      hibernate:
         ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?characterEncoding=utf8&useSSL=true
    river-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    schema:
    data: classpath:db/data.sql

logging:
  level:
    com.androidminds.springstudy: DEBUG
    org.springframework.web: DEBUG
  file:

server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

userservice:
  max-page-count: 50
