spring:
  application:
      name: ZuulService

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

zuul:
  ignoredServices: '*'
  ignoredPatterns: /**/public-key/**
  #prefix: /v1
  routes:
      jwt:
        path: /auth/**
        serviceId: JwtService
      logout:
        path: /auth/logout
        url: forward:/logout
