spring:
  jpa:
    #database: h2
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    #url: jdbc:h2:mem:user
    #driver-class-name: org.h2.Driver
    url: jdbc:mysql://127.0.0.1:3306/userdb?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    data: classpath:db/data.sql
    schema:


logging:
  level:
    com.androidminds.smartservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:

server:
  port: 9030

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

userservice:
  max-page-count: 50
