logging:
  level:
    com.androidminds.springstudy: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: UserService
  jpa:
    open-in-view: true
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    # url: jdbc:mysql://localhost:3306/userdb?characterEncoding=utf8&useSSL=true
    url: jdbc:h2:mem:user
    username: root
    password: 123456
    # data: classpath:db/data.sql
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name:org.h2.Driver

server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

userservice:
  max-page-count: 50
