spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:user
    driver-class-name: org.h2.Driver
    username: root
    password: 123456
    schema:
    data: classpath:db/data.sql

logging:
  level:
    com.androidminds.springstudy: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:

server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

userservice:
  max-page-count: 50
