logging:
  level:
    com.androidminds.smartservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file: /var/smartservice/ZuulService.log

server:
  port: 9090

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

feign:
  hystrix:
    enabled: true

hystrix:
 command:
   default:
     execution:
       timeout:
         enabled: false
       isolation:
         thread:
           timeoutInMilliseconds: 60000


zuul:
  ignoredServices: '*'
  #ignoredPatterns: /**/public-key/**
  #prefix: /v1
  routes:
      jwt:
        path: /auth/**
        serviceId: JwtService
        sensitiveHeaders: Authorization
      logout:
        path: /auth/logout
        url: forward:/logout
  max:
   host:
      connections: 500
      socket-timeout-millis: 60000
      connect-timeout-millis: 60000
