logging:
  level:
    com.androidminds.smartservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:

server:
  port: 9040

web:
  server:
     port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000

jwt:
  password: adfkd#23
  token:
    expire: 1440


