spring:
  application:
    name: ZipkinService
  rabbitmq:
    host: localhost
    port: 5672

server:
  port: 9020

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/