spring:
  application:
      name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: ${config-git-uri:https://github.com/androidminds/SmartService/}
          search-paths: ${config.git.search-paths:Config/*}

logging:
  level:
    com.androidminds.smartservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  file:

server:
  port: 9010

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/