server:
  port: ${port:9000}

spring:
  application:
      name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: ${config.url:https://github.com/androidminds/SmartService/}
          search-paths: ${config.search-paths:config}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/