server:
  port: ${port:9000}

spring:
  application:
      name: ConfigService
  cloud:
    config:
      server:
        git:
          uri: ${config-git-uri:https://github.com/androidminds/SmartService/}
          search-paths: ${config-git-search-paths:Config/*}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/